dist: xenial

language: python

python:
 - "3.7"

addons:
  postgresql: "9.5"

install:
 - pip install psycopg2==2.7.4
 - pip install isort flake8 black
 - pip install codecov
 - pip install -r requirements.txt
 - pip install -r requirements-dev.txt
 - psql -U postgres -c "create database coronacrunch"
 - cp coronacrunch_project/settings/travis.py coronacrunch_project/settings/local.py

script:
 - python manage.py makemigrations --check
 - black --check .
 - flake8 --max-line-length=88 .
 - isort --recursive --check-only --diff .
 - coverage run --include="./*" --omit="*/tests/*","*/tests.py","*/migrations/*","./coronacrunch_project/*" manage.py test -v2

after_success:
 - codecov
